name: Build Registry Files

on:
  push:
    branches:
    - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE: xsf-registrar-master.tar.gz
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install xmllint and xslt utilities
        run: sudo apt-get install -y libxml2-utils xsltproc
      - name: Build files
        run: make all
      - name: Create build archive
        run: tar -czf ${{ env.ARCHIVE }} "./registrar"
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: xsf-registrar-master
          path: ${{ env.ARCHIVE }}
